### ISSUE TITLE
Keyboard onMousePress is not scaling properly

### ISSUE THREAD

**Issue by JoshuaStorm** [JoshuaStorm/WebSynth#1]
The keyboard visual is currently scaling as we want it to, but the notes played are not. 

To quickly reproduce this bug, just open up the p5 sketch and click the left-hand side of the screen. The lowest note in our notes array (MIDI 60, middle C) will play. Obviously, we want this note to play only when the leftmost key is clicked on the screen.

I think I may have forgotten to change the logic in the note played when I did so for the visual.

**Comment by JoshuaStorm** [comment]
@KyleNehman want to check this out?

**Comment by KyleNehman** [comment]
@JoshuaStorm I gotchu
