### ISSUE TITLE
Notes played on (QWERTY) keyboard highlighting piano keys.

### ISSUE THREAD

**Issue by JoshuaStorm** [JoshuaStorm/WebSynth#19]
Similarly to how the keys turn black when clicked, they should turn black when the corresponding QWERTY keyboard key is pressed.

**Comment by KyleNehman** [comment]
@JoshuaStorm What? They do turn black. This is what I spent a while debugging.

**Comment by JoshuaStorm** [comment]
They don't on any device I've tried it on :|

Edit: Yeah I totally introduced this bug by accident, my bad.
