### ISSUE TITLE
Issue with octave change while playing note

### ISSUE THREAD

**Issue by KyleNehman** [JoshuaStorm/WebSynth#87]
Desired behavior:
Changing the octave doesn't affect  notes that are already being played.

Actual behavior:
Notes that are being played's octaves are changing dynamically and can also be cut short if you just tap Z or X instead of holding them.

**Comment by JoshuaStorm** [comment]
Thanks for the writeup. I haven't thought too hard on this, but I think this will actually be a fairly difficult (and/or cumbersome) fix considering how we handle note releases. However, this will also likely resolve some other small issues we're having with note functionality. I might hop on this some weekend if I have a  couple hours.
