### ISSUE TITLE
Type-o in Sketch.JS: "OVTAVE"

### ISSUE THREAD

**Issue by KyleNehman** [JoshuaStorm/WebSynth#92]
Somehow we managed to make a consistent type-o of octave to ovtave in Sketch.js. Should be a simple find and replace with no repercussions.

Honestly just kind of surprised how we let this happen and it didn't cause issues.

**Comment by JoshuaStorm** [comment]
IT IS SPELLED TYPO YOU FILTHY PLEB

**Comment by KyleNehman** [comment]
Whoops, you made a type-o. 

> IT IS SPELLED TYPE-O YOU FILTHY PLEB

FTFY
